---
# tasks file for wp-dependencies

- name: Disable SELinux

  selinux:

    state: disabled


- name: install httpd
  yum:
    name: httpd

- name: Enable service httpd, and not touch the state

  service:

    name: httpd

    enabled: yes


- name: do chmod for/var/www/html

  file:

    path: /var/www/html

    mode: u=rwX,g=rX,o=rX

    recurse: yes


- name: Add remi-php71

  yum_repository:

    name: remi-php71

    description: Remi's PHP 7.1 RPM repository for Enterprise Linux $releasever - $basearch

    mirrorlist: http://rpms.remirepo.net/enterprise/$releasever/php71/mirror

    enabled: yes

    gpgcheck: 1

    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: install php

  yum: name={{item}} state=present

  with_items:  

      - php

      - php-common

      - php-opcache

      - php-cli
      
      - php-curl

      - php-mysql  

 
- name: copy file info.php

  shell: echo "<?php phpinfo (); ?>" > /var/www/html/info.php



- name: restart httpd

  service:

        name: httpd

        state: restarted
